INSERT INTO PROJECT(ID, NAME) VALUES('p-1','Aby');
INSERT INTO PROJECT(ID, NAME) VALUES('p-2','Ben');
INSERT INTO PROJECT(ID, NAME) VALUES('p-3','ABC');
INSERT INTO PROJECT(ID, NAME) VALUES('p-4','DDD');
